#!/bin/bash

git config --global user.name “[Khumbulani Mavundla]”
#set a name that is identifiable for credit when review version history
git config --global user.email “[khumbulani@kartoza]”
#set an email address that will be associated with each history marker
git config --global color.ui auto
#set automatic command line coloring for Git for easy reviewing
